# Generated by Django 3.2.7 on 2021-10-15 19:04

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_room_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default=api.models.generate_room_code, max_length=6, unique=True),
        ),
    ]
